### ISSUE TITLE
[Issues] Phantom items | Block breaking time

### ISSUE THREAD

**Issue by accessdenied0** [HlaaftanasAccounts/Multi-Dimensional-Ores#1]
Hello @hlaaftana,

I use you mod currently and run into some issues:

First, if you smelt some of the Nether-ores you get "Phantom items" as result. What this means: You get seemingly the result of the smelting (but only one for one) but these Items are none existent and vanish if you use them in any way.  

Second, the block-hardness is by every block the same (instant).

Third (optional), the block generation of these ores is active nevertheless if there are needed or not... I use Extra TiC and some of the metals are needed but not all of them.

Thank you for your help,

access_denied

**Comment by hlaaftana** [comment]
First error fixed: I called the block/item/recipe register methods before I called the config class, which had the output amounts set as 0. Therefore the stack number of the items were 0, causing them to be phantoms.

Second one was intended because vanilla does the same thing. I still did optimize my hardness code to fit the vanilla standards.

I do not get your third issue. Do you mean the worldgen options in the configs don't work?

**Comment by accessdenied0** [comment]
Hey @hlaaftana,

yeah, I was a bit unclear here... My third issue is that I get more ore generation than needed. I'm not sure if ExtraTiC causes some register issues but I can't use most of the ores/ingots. Is this manual or do you intent to add some tools for these Ingots?

Anyway it is not really a "issue"... more a question. But I'm very thank full for fixing my first issue here it was pretty annoying... 

thank you a lot

access_denied

**Comment by hlaaftana** [comment]
Huh... End and Nether ores won't work in ExtraTiC for sure (unless their outputs are set to 1). Perhaps ExtraTiC screwed something up. Because it's not open source, can't really help you with it. Perhaps beta 2 will fix it, but i won't be releasing that very soon because of the vast amount of textures i need to make

**Comment by accessdenied0** [comment]
@hlaaftana,

Oh, you mean I can't smelt them in Tinkers Construct? I was thinking of using them as material for tools and weapons. Even the ingots are correctly OD-registered, are not completely usable even with ExtraTiC. For example Titanium, but even I can't use it, it is generated.

access_denied

**Comment by hlaaftana** [comment]
I remember something about ExtraTiC not being compatible with a mod's ingots. Possibly not my fault, but i do recommend [this](http://www.curse.com/mc-mods/minecraft/227564-oredictionaryconverter)

**Comment by accessdenied0** [comment]
@hlaaftana,

Yeah, I had the feeling. I was not sure about this but anyway. I use this, but I do not have alternatives installed. What means your ingots are (currently) the only ones in my MC-instance (Except Copper or Tin).

anyway, thank you a lot for your help,

access_denied
